# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170908_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title2',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
