# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_post_title2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title2',
        ),
        migrations.AddField(
            model_name='post',
            name='menu',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
