# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170908_2327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Musician',
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='static/bg/'),
        ),
    ]
